CUDA_VISIBLE_DEVICES=1 python main_block_ap.py --model  /home/nku509/models/llama/llama3/llama3.1_8b_hf \
 --output_dir ./output/block_ap_log/Llama-3.1-8b-w2.75g128 \
 --net Llama-3 \
 --calib_dataset c4 \
 --wbits 2.75 \
 --group_size 128 \
 --quant_lr 1e-4 \
 --weight_lr 2e-5 \
 --train_size 4096 \
 --eval_ppl \
 --epoch 2 \
 --real_quant \
 --save_quant_dir ./output/block_ap_models/Llama-3-8b-w2.75g128 \
 --sensitivity_path /home/nku509/llama3_8b_importance \
 --off_load_to_disk \
 --off_load_batch_size 256 \